### ISSUE TITLE
Causes zram to be unusable

### ISSUE THREAD

**Issue by cynide00** [JoshuaDoes/ptune#1]
![Screenshot_20241109-133501](https://github.com/user-attachments/assets/41ffd717-069c-4f55-b9cf-a5ff5015f4e8)
After using the module, zram is always unused, even if the physical memory usage is already high

**Comment by Xerxes-2** [comment]
> we're also setting the swappiness value to 1 so that zram is avoided until it's absolutely necessary

As said in README
